# =============================================================
# 🚀 TALKIE — PRO FLUTTER LINT CONFIG
# =============================================================

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
    - "**/*.mocks.dart"

linter:
  rules:
    # ===========================
    # 🧱 CONST + IMMUTABILITY
    # ===========================
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    unnecessary_const: false
    use_key_in_widget_constructors: true
    always_declare_return_types: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true

    # ===========================
    # ⚙️ PERFORMANCE RULES
    # ===========================
    avoid_unnecessary_containers: true
    avoid_redundant_argument_values: true
    avoid_unnecessary_setstate: true
    sized_box_for_whitespace: true
    use_decorated_box: true
    use_repaint_boundary: true
    prefer_single_quotes: true
    unnecessary_parenthesis: true
    use_super_parameters: true
    prefer_interpolation_to_compose_strings: true

    # ===========================
    # 🧠 REBUILD SAFETY
    # ===========================
    avoid_classes_with_only_static_members: false
    avoid_returning_null: true
    avoid_field_initializers_in_const_classes: true
    avoid_shadowing_type_parameters: true
    avoid_init_to_null: true
    avoid_positional_boolean_parameters: true

    # ===========================
    # 🎨 STYLE + READABILITY
    # ===========================
    annotate_overrides: true
    curly_braces_in_flow_control_structures: true
    sort_child_properties_last: true
    prefer_expression_function_bodies: true
    prefer_typing_uninitialized_variables: true
    avoid_empty_else: true
    prefer_relative_imports: true
    directives_ordering: true
    always_put_required_named_parameters_first: true
    always_put_control_body_on_new_line: true
    require_trailing_commas: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true

    # ===========================
    # 🧹 CLEAN CODE + SAFETY
    # ===========================
    avoid_print: true
    avoid_unnecessary_type_assertions: true
    avoid_unnecessary_this: true
    unnecessary_late: true
    use_late_for_private_fields_and_variables: true
    avoid_bool_literals_in_conditional_expressions: true
    prefer_for_elements_to_map_fromIterable: true
    unawaited_futures: true
    use_is_even_rather_than_modulo: true
    cascade_invocations: true

    # ===========================
    # 🧩 FLUTTER SPECIFIC
    # ===========================
    avoid_returning_widgets: false
    avoid_unnecessary_rebuilds: true
    avoid_expensive_operations_in_build: true
    avoid_unnecessary_overrides: true
    use_build_context_synchronously: true
    avoid_web_libraries_in_flutter: true

    # ===========================
    # 🧪 TESTING / MAINTAINABILITY
    # ===========================
    avoid_renaming_method_parameters: true
    avoid_slow_async_io: true
    prefer_asserts_with_message: true
    prefer_asserts_in_initializer_lists: true
    prefer_null_aware_method_calls: true
    avoid_catching_errors: true
